version: '3'

services:

  redis:
    image: redis

  worker:
    build: .
    depends_on:
      - redis
    environment:
      RQ_REDIS_URL: redis://redis
    command: python worker.py
    volumes:
      - .:/app
    working_dir: /app

